Microsoft/HoloJS

HoloJS/HoloJsHost/ScriptingFramework/DOM.js
HoloJS/HoloJsHost/System.cpp
HoloJS/HoloJsHost/System.h

This only works only when doing native debugging.

Redirect console.[log|...] to OutputDebugString to make it available in VS's output window

---

README.md

The link was broken up due to the linebreak & spaces between the user-facing text ("Enable your device for development") and the actual link.

Fix link in "Deploying" section of readme

---

HoloJS/ThreeJSApp/Scripts/app.js

window.experimentalHolographic should be used to check when running in a holographic environment. If it is not set, fallback to the perspective camera.
This also fixes the JS warnings for failing to invert a matrix.

Use a perspective camera in the ThreeJS sample when not running in a holographic environment

---

HoloJS/HoloJsHost/HologramJS.h
HoloJS/HoloJsHost/KeyboardInput.cpp
HoloJS/HoloJsHost/KeyboardInput.h
HoloJS/HoloJsHost/MouseInput.cpp
HoloJS/HoloJsHost/MouseInput.h
HoloJS/HoloJsHost/RenderingContext2D.cpp
HoloJS/HoloJsHost/ScriptingFramework/FrameworkHelpers.js
HoloJS/HoloJsHost/ScriptingFramework/Window.js
HoloJS/HoloJsHost/pch.h
HoloJS/ThreeJSApp/Scripts/OrbitControls.js
HoloJS/ThreeJSApp/Scripts/app.js
HoloJS/ThreeJSApp/Scripts/app.json
HoloJS/ThreeJSApp/ThreeJSApp.vcxproj
HoloJS/ThreeJSApp/ThreeJSApp.vcxproj.filters

Mouse and keyboard input was not captured when running on desktop. This change captures mouse and keyboard input from the current window.
Fix issues related to routing input to the scripting guest: JsValueRef values got garbage collected unintended, causing AVs.  Changed to code to allocate arrays of JsValueRefs on the stack to prevent garbage collection.
Add OrbitControl.js to enable mouse camera control in the ThreeJS app when running on desktop.
Fix misc compiler warnings.
Bubble mouse events to "document", not just "canvas".

Fix mouse and keyboard input when running on desktop

---

HoloJS/HoloJsHost/HoloJsHost.vcxproj
HoloJS/HoloJsHost/HoloJsHost.vcxproj.filters
HoloJS/HoloJsHost/HologramJS.cpp
HoloJS/HoloJsHost/HologramJS.h
HoloJS/HoloJsHost/InputInterface.h
HoloJS/HoloJsHost/KeyboardInput.cpp
HoloJS/HoloJsHost/KeyboardInput.h
HoloJS/HoloJsHost/MouseInput.cpp
HoloJS/HoloJsHost/MouseInput.h
HoloJS/HoloJsHost/ScriptingFramework/Window.js
HoloJS/HoloJsHost/SpatialInput.cpp
HoloJS/HoloJsHost/SpatialInput.h
HoloJS/HoloJsHost/WindowElement.cpp
HoloJS/HoloJsHost/WindowElement.h
HoloJS/HoloJsHost/pch.h
HoloJS/SampleApp/App.cpp
HoloJS/SampleApp/Scripts/app.js
HoloJS/ThreeJSApp/App.cpp
HoloJS/ThreeJSApp/Scripts/app.js

Make spatial input available to JavaScript.
Registering for spatial input is done through <canvas_element>.addEventListener("spatialinput", ...)
The event callback get a spatialInputEvent parameter containing:
- isPressed bool property
- location property: {x, y, z}
- kind property: controller, hand, voice, other. See [https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.spatial.spatialinteractionsourcekind] for details
The input coordinates are relative to the original stationary frame of reference - the origin of the scene.

Spatial input is available in JavaScript

---

HoloJS/ThreeJSApp/Scripts/app.js

It is too CPU intensive and causes frame rate drops.
Without the raycaster, the sample runs at 60 fps.
With the raycaster, the sample runs between 18 and 60 fps.

Remove raycaster from the ThreeJS sample

---

HoloJS/HoloJsHost/SpatialInput.cpp
HoloJS/HoloJsHost/SpatialInput.h
HoloJS/HoloJsHost/WindowElement.cpp

Explicitly request spatial input callbacks on the current thread at registration time.
In RS1, callbacks are delivered on random threads and the JS context is bound to the UI thread.
In RS2, callbacks are already delivered on the same thread as registration, so this change is a no-op.

Explicitly execute spatial input callbacks on the JS thread

---

HoloJS/HoloJsHost/HoloJsHost.vcxproj
HoloJS/HoloJsHost/HoloJsHost.vcxproj.filters
HoloJS/HoloJsHost/InputInterface.h
HoloJS/HoloJsHost/ScriptingFramework/Window.js
HoloJS/HoloJsHost/SpatialMapping.cpp
HoloJS/HoloJsHost/SpatialMapping.h
HoloJS/HoloJsHost/WindowElement.cpp
HoloJS/HoloJsHost/WindowElement.h
HoloJS/ThreeJSApp/Package.appxmanifest
HoloJS/ThreeJSApp/Scripts/app.js

Implement retrieval of spatial mapping data from script.
The script can specify the extents from the origin of the scene to include in the scan. The script can also request a triangle density.
Upon spatial mapping data becoming available, the specified callback is invoked, one scanned surface at a time. Indices, vertexes, normals and the transform to origin of the surface is provided.
Added ThreeJS sample for constructing a Mesh object from the received data. Two methods for building geometry from the buffers are provided. The buffered mode is faster, the basic Geometry mode is slower but allows arbitrary manipulation of the data before rendering.
Mapping data is processed off the UI thread to not block rendering; after the data is available, callbacks into the script are done on the UI …

Spatial mapping data is available to scripts

---

HoloJS/HoloJsHost/ScriptsLoader.cpp

For a local app.json, allow adding web scripts to the list of scripts to be loaded.
Web scripts must be added using a full URI - relative paths won't work for web scripts in local apps.

Allow mixing local and web scripts in app.json

---

HoloJS/HoloJsHost/ScriptingFramework/DOM.js
HoloJS/HoloJsHost/ScriptingFramework/XmlHttpRequest.js
HoloJS/HoloJsHost/ScriptsLoader.cpp
HoloJS/HoloJsHost/System.cpp
HoloJS/HoloJsHost/System.h
HoloJS/HoloJsHost/XmlHttpRequest.cpp
HoloJS/HoloJsHost/XmlHttpRequest.h

clearTimeout and some XHR methods were missing and prevented socket.io to work properly.
Catch exceptions in HttpClient::GetAsync; they become XHR errors and don't crash the host.

Implement more timers and XHR methods to fix socket.io

---

HoloJS/HoloJsHost/HoloJsHost.vcxproj
HoloJS/HoloJsHost/HoloJsHost.vcxproj.filters
HoloJS/HoloJsHost/HologramJS.cpp
HoloJS/HoloJsHost/HologramJS.h
HoloJS/HoloJsHost/KeyboardInput.cpp
HoloJS/HoloJsHost/MouseInput.cpp
HoloJS/HoloJsHost/ObjectEvents.h
HoloJS/HoloJsHost/ScriptErrorHandling.h
HoloJS/HoloJsHost/ScriptsLoader.cpp
HoloJS/HoloJsHost/ScriptsLoader.h
HoloJS/HoloJsHost/SpatialInput.cpp
HoloJS/HoloJsHost/SpatialMapping.cpp
HoloJS/HoloJsHost/System.cpp
HoloJS/HoloJsHost/WindowElement.cpp
HoloJS/HoloJsHost/pch.h

At the moment, if there's a mistake in the JavaScript code, there's no useful feedback about what went wrong making debugging difficult. This pull request provides the developer with a normal JavaScript exception error.

Print JS Exceptions to console.

---

HoloJS/HoloJsHost/ScriptingFramework/Canvas2D.js
HoloJS/HoloJsHost/ScriptingFramework/Image.js

CanvasRenderingContext2D drawImage parameter passing from script to native was broken for
drawImage(image, dx, dy, dWidth, dHeight);
drawImage(image, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight);
HTMLImageElement was not implemented. Now it is defined identical to an Image element to make ThreeJS happy on its image resizing path.

Fix image resizing in ThreeJS

---

HoloJS/HoloJsHost/HoloJsApp.cpp
HoloJS/HoloJsWebViewer/app.cpp
WebSamples/index.html

web-ar links should be able to explicitly specify the protocol for retrieving the json file (e.g. webar:https://holojs.azurewebsites.net/samples/photosphere/photosphere.json) and not be forced to plain http

Don't force http protocol on web-ar links

---

HoloJS/HoloJsWebViewer/app.cpp

There was a breaking change in protocol activation. The previously published content no longer loads in the latest viewer (and the other way around).
A new version of the web samples were published to http://holojs.azurewebsites.net/v1/samples/ and the viewer is updated to point to this version. Previous versions of the viewer will continue to work, loading content from the previous version of the web samples.

Point the viewer to versioned web content

---

HoloJS/HoloJsHost/ImageElement.cpp
HoloJS/HoloJsHost/ObjectEvents.h
HoloJS/HoloJsHost/VideoElement.cpp
HoloJS/HoloJsHost/XmlHttpRequest.cpp

JsValueRef has auto-cleanup methods when it goes out of scope. When passing these types in std::vector arrays, they get released and upon being accessed on the script side they can cause bogus memory reads or crashes. The fix is to call the callback function from the same context where the parameters are declared.

Fix crash on image load

---

HoloJS/HoloJsHost/System.cpp
HoloJS/HoloJsHost/System.h

Fixes #104 
A promise continuation callback was not registered in native code, which caused resolve/reject in script to throw exceptions.

Add promise continuation callback in native code

---

HoloJS/HoloJsHost/ScriptingFramework/DOM.js
HoloJS/HoloJsHost/XmlHttpRequest.cpp
HoloJS/HoloJsHost/XmlHttpRequest.h

Remove proxy-ing from DOM.JS. The intent of the proxy is to hide internal DOM implementation from scripts, as per W3 spec. However, that is not a goal in HoloJS and proxying can be taken out.
Remove global.location and window.location from the DOM. It confuses socket.io into thinking a cross domain request is required, and JSONP is not supported in HoloJS.
Fix a bug in XmlHttpRequest where setting content type on HttpStringContent would cause a crash.
With the above fixes, socket.io's chat sample appears to be working.

Fix DOM and XHR issues to make socket.io work

---

HoloJS/HoloJsHost/HoloJsApp.cpp
HoloJS/HoloJsHost/HoloJsApp.h
HoloJS/HoloJsHost/HoloJsHost-Vs2017.vcxproj
HoloJS/HoloJsHost/SpatialInput.cpp
HoloJS/HoloJsHost/SpatialMapping.cpp
HoloJS/HoloJsWebViewer/HoloJsWebViewer-Vs2017.vcxproj
HoloJS/SampleApp/SampleApp-Vs2017.vcxproj
HoloJS/ThreeJSApp/App.cpp
HoloJS/ThreeJSApp/ThreeJSApp-Vs2017.vcxproj

Disclaimer: for now tracking is sub-par on Mixed Reality headsets and stops working if the rendered scene goes out of view completely. These will be addressed later.
HoloJS runs as a flat app on Mixed Reality (MR) headsets. Rev the target platform to RS3 such that the holographic space can be created on desktop as well (not just HoloLens), and the app will run in holographic mode.
Added a LaunchMode option to the HoloJsApp class. The app can specify what kind of view to be created:
1. AsActivated: create a view that matches the launch context: flat on desktop, holographic on HoloLens and MR headset
2. Holographic: attempt to create a holographic view even when the app is launched from the desktop. The app view will be created in the MR headset.
3. Flat: create a flat view regardless on …

Enable holographic mode when running on Mixed Reality headsets

---

HoloJS/HoloJsHost/HoloJsApp.cpp
HoloJS/HoloJsHost/HoloJsHost.vcxproj

VS 2015 does not work with Windows SDK 16299. Add a #define to avoid compiling code. When building with VS2015 the target SDK version for HoloJS remains 14393.

Use #define to avoid compilation of RS3 API in the VS2015 solution

---

HoloJS/HoloJsHost/XmlHttpRequest.cpp
HoloJS/HoloJsHost/XmlHttpRequest.h

Setting content headers was not working for all content type (buffer). Added a more robust (but still incomplete) implementation.

Fix adding content headers

---

HoloJS/HoloJsHost/ImageElement.cpp

A reference on the image buffer is released prematurely.

Fix AV in ImageElement when the image source is the webcam

---

HoloJS/HoloJsHost/ImageElement.cpp
HoloJS/HoloJsHost/ScriptingFramework/XmlHttpRequest.js
HoloJS/HoloJsHost/VideoElement.cpp
HoloJS/HoloJsHost/WebSocket.cpp
HoloJS/HoloJsHost/XmlHttpRequest.cpp

Working on a project that uses HoloJS with frequent XmlHttpRequests to update positions of the object being displayed (about 30 updates per second). Kept running into intermittent crashes, typically in XmlHttpRequest::FireStateChanged, sometimes during timer updates, sometimes the responseType string ended up corrupt rather than "text".
After a bunch of debugging I found that one or more of the objects in the vector of JsValueRef parameters was being unexpectedly garbage collected before JsCallFunction completed. To prevent garbage collection the hosted chakra.dll needs to have have an active reference or be able to see it on the stack. Since the contents of the "vector" are on the heap, it didn't see them so there is a very small window where the object could be incorrectly garbage …

Fix for XmlHttpRequest Crash

---

HoloJS/HoloJsHost/HoloJsHost-Vs2017.vcxproj
HoloJS/HoloJsHost/SpatialInput.cpp
HoloJS/HoloJsHost/SpatialInput.h
HoloJS/HoloJsHost/SpatialMapping.cpp
HoloJS/HoloJsWebViewer/HoloJsWebViewer-Vs2017.vcxproj
HoloJS/SampleApp/SampleApp-Vs2017.vcxproj
HoloJS/ThreeJSApp/ThreeJSApp-Vs2017.vcxproj

There was no persisted reference to the SpatialInteractionManager, which causes event registration to be dropped on build 17720.
Also target the RS4 SDK and fix an AV in spatial mapping.

Fix spatial input
